# Generated by Django 5.2.8 on 2025-11-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('content', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatprompt',
            name='model_response',
        ),
        migrations.CreateModel(
            name='ModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Courses.lessonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=80)),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Courses.modulemodel')),
            ],
        ),
    ]
