# Generated by Django 5.2.8 on 2025-11-20 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_customuser_courses'),
        ('Courses', '0002_lessonmodel_remove_chatprompt_model_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemodel',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='modules',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Auth.customuser'),
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Courses.coursemodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LessonModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(default='lecture', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Courses.modulemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='LessonModel',
        ),
    ]
