# Generated by Django 5.2.8 on 2025-11-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_remove_modulemodel_lessons_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonModule',
            new_name='LessonModel',
        ),
        migrations.AlterField(
            model_name='modulemodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Courses.coursemodel'),
        ),
    ]
