# Generated by Django 5.2.8 on 2025-11-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_customuser_courses'),
        ('Courses', '0004_rename_lessonmodule_lessonmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Auth.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modulemodel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Courses.coursemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modulemodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
