# Generated by Django 5.2.8 on 2025-12-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_coursemodel_owner_alter_coursemodel_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Домашнє завдання', max_length=255)),
                ('content', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='Courses.modulemodel')),
            ],
        ),
    ]
