# Generated by Django 5.2.8 on 2025-12-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_homeworkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmodel',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='user_submission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
