# Generated by Django 5.2.8 on 2025-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_homeworkmodel_ai_feedback_homeworkmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
