# Generated by Django 5.2.8 on 2025-11-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_customuser_tokens_tokentransaction'),
        ('Courses', '0002_lessonmodel_remove_chatprompt_model_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Courses.coursemodel'),
        ),
        migrations.DeleteModel(
            name='TokenTransaction',
        ),
    ]
