# Generated by Django 5.2.8 on 2025-11-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_customuser_courses_delete_tokentransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
    ]
