# Generated by Django 5.2.8 on 2025-11-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tokens',
        ),
    ]
