# Generated by Django 5.2.8 on 2025-12-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_remove_customuser_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak_days',
            field=models.IntegerField(default=0, help_text='Кількість днів поспіль'),
        ),
    ]
